### PR TITLE
The default spark application name for Toree is still IBM Spark Kernel.

### PR DESCRIPTION
**Pull request by mariusvniekerk**
Lets fix that.

### CODE REVIEW

**Comment by mariusvniekerk** [comment]
I can cherry pick this for 0.1x if we want.

**Comment by mariusvniekerk** [comment]
@chipsenkbeil Ready for review since this is just a one-line string change.

**Comment by chipsenkbeil** [comment]
Ha ha, I had forgotten about this. Good catch. Yeah, we should backport this into the 0.1 branch as well. Don't want a release without the proper name.

**Comment by mariusvniekerk** [comment]
I see that is also done in #51, but not sure on the status of that PR

**Comment by chipsenkbeil** [comment]
A one-liner will be simple enough to rebase on top of, so I'm not worried. That reminds me that I was supposed to follow up on that.

**Pull request merged**
