### PR TITLE
TOREE-391 Treat zmq ids as bytes

### PR DESCRIPTION
**Pull request by jrhyness**

### CODE REVIEW

**Comment by mariusvniekerk** [comment]
Not quite sure why the CI build hasn't started.

**Comment by lbustelo** [comment]
@jrhyness Apparently Travis had issues during compilation... https://travis-ci.org/apache/incubator-toree/builds/209588806#L2687

Maybe there some changes needed in other projects.

**Comment by lbustelo** [comment]
@mariusvniekerk I'm trying to test this branch. I typically rely on `make jupyter` to setup a clean notebook with toree... I'm not able to get it to complete the build. Are you able to run `make jupyter`?

**Comment by jrhyness** [comment]
Thanks @lbustelo .  

I have committed some changes to the tests.  There are still failures though.  Trying to work through the scalatest object matching...

I realize that changing the tests is not ideal but I think it is required.  I don't believe the ids should be treated as strings.  What I want to know is if I can do this at all ( make ids Array[Byte] ) or if it is a breaking change and allso, if there is a better approach.

**Comment by lbustelo** [comment]
I say changing the test is fine. For me the real test is to make sure that all is still working when connecting the notebook. I'm going to give that a try here... (now that I can build!).

**Comment by lbustelo** [comment]
I did a quick test on this branch running the notebook and did not see any issues.

**Comment by kevin-bates** [comment]
fwiw - I patched my fork with these changes and found I could perform the various restart operations under the kernel tab - which wasn't the case before.  Nice find!

**Comment by lresende** [comment]
@jrhyness  Is this still a [WIP] ?

**Comment by jrhyness** [comment]
@lresende Yes it is.  I'm trying to get the tests passing.  I think I need a KernelMessage.equals .

**Comment by jrhyness** [comment]
@lresende , @lbustelo .  I think I'm ready for review now.  Thanks.  /J

**Comment by lresende** [comment]
LGTM, verified trough few notebook examples and restart scenarios.
Merging if there are no more comments

**Comment by jrhyness** [comment]
@lresende Do you know when there will be another 0.2.0 (pre)release?

**Comment by lresende** [comment]
I would recommend you building it yourself from master.

**Pull request closed without merging**
