### PR TITLE
Moving from a Build.scala file to a build.sbt file.

### PR DESCRIPTION
**Pull request by fiskl**
I've trying to shift the build information to a build.sbt file, which is easier to read and understand.

### CODE REVIEW

**Comment by fiskl** [comment]
Currently WIP, need to get the makefile to use the new build.sbt

**Comment by chipsenkbeil** [comment]
@lbustelo, @Lull3rSkat3r, this is pretty nice considering sbt 1.0+ has removed support for `Build.scala` in favor of `build.sbt`. So, we'll need to do this eventually.

**Comment by Lull3rSkat3r** [comment]
LGTM, the only feedback I have is about the `BuildInfo` class. It looks like the package name was changed. If we can we should not move the package as to not break any references people have to that class. Otherwise great job!

**Comment by fiskl** [comment]
I've rewritten history and moved the BuildInfo package back to org.apache.toree.kernel.

**Comment by chipsenkbeil** [comment]
LGTM

**Pull request merged**
