### PR TITLE
Updated .travis.yml to test the 0.1.x branch

### PR DESCRIPTION
**Pull request by lbustelo**

### CODE REVIEW

**Comment by lbustelo** [comment]
Look at that... tests!

**Comment by mariusvniekerk** [comment]
yeah for the spark 2.0 branch i stopped using coursier at build time,  was just too unreliable and gave non-useful errors.

**Comment by lbustelo** [comment]
Hmm. Ok then. Not really sure what I changed that is tied to using coursier.

**Comment by mariusvniekerk** [comment]
Try removing coursier from the plugins.sbt.  That made most of my decency issues go away on master

**Comment by chipsenkbeil** [comment]
LGTM

**Pull request merged**
