### PR TITLE
TOREE-389: Ensure bindings are run before user code.

### PR DESCRIPTION
**Pull request by rdblue**

### CODE REVIEW

**Comment by mariusvniekerk** [comment]
What does this change?

**Comment by rdblue** [comment]
This binds `spark` before this runs:

```
    logger.info("Marking relay as ready for receiving messages")
    kernelMessageRelayActor ! true
```

That way if a cell was submitted during kernel startup, it can't run and fail. This prevents the interpreter hanging, which is a larger issue described on TOREE-389.

**Comment by mariusvniekerk** [comment]
Ah, yeah that's a pain.

**Comment by mariusvniekerk** [comment]
So the tests for this hung?  Dan you run these locally on your own system?  Alternatively closing and reopening will kick travis into restarting them.

**Pull request merged**
