### PR TITLE
TOREE-376: Add implicits to the Scala interpreter.

### PR DESCRIPTION
**Pull request by rdblue**
This defines Scala implicits commonly used with Spark SQL. This includes dataframe functions, like `map` or `sum`, common conversions like `Seq#toDF`, and the `$` prefix to coerce strings to column names.

### CODE REVIEW

**Comment by rdblue** [comment]
It looks like the build is failing, but not from this patch. The scala tests are all passing. I'm also happy to add a test for this, if someone can tell me where it should go.

**Comment by chipsenkbeil** [comment]
@mariusvniekerk, does this look good to you? If so, @rdblue, can you rebase this?

**Comment by rdblue** [comment]
Rebased

**Comment by mariusvniekerk** [comment]
Okay looks good to me.  I think we did this initially to limit the size of the classes that got generated.  However the quality of life improvement that this gives is worth it IMO.

**Comment by chipsenkbeil** [comment]
There may be other tricks we can do to reduce the generated classes as well, so I'll merge this in. Thanks @rdblue and @mariusvniekerk!

**Comment by rdblue** [comment]
Thank you @chipsenkbeil and @mariusvniekerk for reviewing!

**Pull request merged**
