### PR TITLE
Added functions to send rich display content to client

### PR DESCRIPTION
**Pull request by lbustelo**
This PR adds a couple of functions to the `kernel` object to enable sending rich content to the client. For now it is supporting HTML and Javascript, but also has a generic method to send content of any mime-type that the client can handle.

### CODE REVIEW

**Comment by lbustelo** [comment]
fixes https://issues.apache.org/jira/browse/TOREE-258

**Comment by lbustelo** [comment]
Still need to add tests.

@chipsenkbeil Can you take a quick look? Most importantly, I had to add support to save off `_lastKernelMessage` in the Comm messages.

**Comment by lbustelo** [comment]
Tests are in. removing the WIP status

**Comment by chipsenkbeil** [comment]
@lbustelo looked it over and everything checks out to me.

**Comment by lbustelo** [comment]
@chipsenkbeil so no issues with storing the comm request as parents?

**Comment by chipsenkbeil** [comment]
@lbustelo, I don't think so. We just use that to allow you to keep track of a specific parent header when creating streaming messages. That's kept in a closure with the stream once started, so I don't think a comm message will hurt it. If you want to be safe, create another global that holds on to the last comm kernel message instead of execution request kernel message.

**Comment by lbustelo** [comment]
Ok.. merged

**Pull request merged**
