### PR TITLE
[TOREE-340] Make truncation regex non-greedy

### PR DESCRIPTION
**Pull request by jodersky**
Fixes cases in which a result containing and "=" would also be truncated.

**Note the fix is in the second commit.** I couldn't stop myself for the first, purely cosmetic commit, but 3 spaces as indentation just seems wrong.

### CODE REVIEW

**Comment by jodersky** [comment]
Travis log:
```
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.

The following information may help to resolve the situation:
The following packages have unmet dependencies:
 openjdk-8-jre-headless : Breaks: ca-certificates-java (< 20160321~) but 20140324 is to be installed
```
Maybe this is temporary; could someone with admin privileges rerun the build?

**Comment by mariusvniekerk** [comment]
Simplest way to rerun the build is to close and reopen the PR.

**Comment by jodersky** [comment]
nice trick, thanks!

**Comment by jodersky** [comment]
looks like the build failure is due to http://unix.stackexchange.com/questions/342403/openjdk-8-jre-headless-depends-ca-certificates-java-but-it-is-not-going-to-be

**Comment by mariusvniekerk** [comment]
I recommend we close this PR in favor of #104

**Comment by jodersky** [comment]
agreed

**Pull request closed without merging**
