### PR TITLE
[TOREE-281] Fix typos in docs/comments/testnames.

### PR DESCRIPTION
**Pull request by dongjoon-hyun**

### CODE REVIEW

**Comment by Lull3rSkat3r** [comment]
@dongjoon-hyun, is this all good to go?  I can merge if it is ready.

**Comment by dongjoon-hyun** [comment]
Oh, yes. That's all for me. Please merge this.
Thank you for review, @Lull3rSkat3r !

**Comment by chipsenkbeil** [comment]
@dongjoon-hyun, even though it's just comments, do you mind rebasing on top of master? Only difference is the changes from your other PR I just merged in. We're trying to keep a clean(er) commit log going forward.

**Comment by dongjoon-hyun** [comment]
Oh, sure, no problem!

**Comment by dongjoon-hyun** [comment]
I rebased this to the master again.

**Comment by chipsenkbeil** [comment]
@dongjoon-hyun, thanks! @Lull3rSkat3r will be getting to this one soon.

**Comment by Lull3rSkat3r** [comment]
Merged, thanks for the contribution @dongjoon-hyun

**Comment by dongjoon-hyun** [comment]
Thank you for merging, @Lull3rSkat3r and @chipsenkbeil .

**Pull request merged**
