### PR TITLE
Add Flush Method to Logger so it can be compliant to stream interface: JIRA TOREE-356 and TOREE-357

### PR DESCRIPTION
**Pull request by DTAIEB**
Logger doesn't have the flush method which is causing an exception when I try to use it as a stream for my project.

### CODE REVIEW

**Comment by DTAIEB** [comment]
There are 2 minor code changes in this PR:
-Add Flush Method to Logger object so it can be compliant with stream interface
-In the loop that pull code_info from the queue, make sure we have a new code_info before setting the current one to null. Reason is that in some cases (say Spark Streaming for example), the cell may have finished executing but there is still data coming down

**Comment by mariusvniekerk** [comment]
Looks good to me

**Comment by mariusvniekerk** [comment]
Can you make an issue on the Toree JIRA for this and link it in your PR title?

**Comment by lbustelo** [comment]
@mariusvniekerk If this looks good to you. I think you should do the merge.

**Comment by rgbkrk** [comment]
:shipit:

**Pull request merged**
