### PR TITLE
[TOREE-508] Reply errors to iopub.error instead of iopub.exec_result

### PR DESCRIPTION
**Pull request by gmcoringa**
Fix string values within Metadata, the values needs to be json string.
Reply errors to iopub.error instead of iopub.exec_result

### CODE REVIEW

**Comment by lresende** [comment]
I believe we are going in the right direction here, but with the change on behavior the errors are not completely showing up on the notebook interface.

Original behavior:
toree-508-original

And with the changes from this pr:
toree-508-updated

As shown in the picture above, the contents are not all there, and the cell is not scrollable anymore.

**Comment by gmcoringa** [comment]
> I believe we are going in the right direction here, but with the change on behavior the errors are not completely showing up on the notebook interface.
> 
> Original behavior:
> toree-508-original
> 
> And with the changes from this pr:
> toree-508-updated
> 
> As shown in the picture above, the contents are not all there, and the cell is not scrollable anymore.

The error is not completely showing because of the code below found in [ScalaInterpreterSpecific.scala#L429](https://github.com/apache/incubator-toree/blob/master/scala-interpreter/src/main/scala-2.11/org/apache/toree/kernel/interpreter/scala/ScalaInterpreterSpecific.scala#L429):
```java
        ExecuteError(
          ex.getClass.getName,
          ex.getLocalizedMessage,
          formattedException.slice(1, formattedException.size - 1).toList
        )
```
Which removes the first line from the stack, I don't know why, but I believe that this should not be done.

About the scrollable, testing with python kernels seems to have the same behaviour (errors are not scrollable).

So @lresende if you think its better I can fix the removal of messages from the stack trace.

**Comment by lresende** [comment]
@gmcoringa Yes, please update with the fix for the removal of the message.

**Comment by gmcoringa** [comment]
@lresende fix done, also I did another commit to fix some unit tests, but there are other testing failing, that I couldn't understand why.

**Comment by gmcoringa** [comment]
> @lresende fix done, also I did another commit to fix some unit tests, but there are other tests failing, that I couldn't understand why.

Another point is that I was not able to reproduce the error.

**Pull request merged**
