### PR TITLE
Adding binder support to simplify consumption of examples and play wi…

### PR DESCRIPTION
**Pull request by lbustelo**
This adds support to run our repo as a Binder in mybinder.org.

To see how this works, go to https://github.com/lbustelo/incubator-toree and click `Binder` badge in the README or go to http://mybinder.org/repo/lbustelo/incubator-toree.

### CODE REVIEW

**Comment by lbustelo** [comment]
@chipsenkbeil or @Lull3rSkat3r Please review

**Comment by chipsenkbeil** [comment]
Looks fine to me. Already tried the badge from your fork and it launched a notebook. Just to make sure, the intention is for it to launch a Python3 kernel whose notebook contains a link to the notebook listing with the example Toree notebook, right?

**Comment by lbustelo** [comment]
Yeah. I think that would be best. No need to start a Toree kernel just for markdown. 

Gino B.

**Comment by chipsenkbeil** [comment]
Cool. I'll merge this one tomorrow.

**Pull request merged**
