### PR TITLE
[WIP] Package fixes based on feedback on 0.1.0 rc1

### PR DESCRIPTION
**Pull request by lbustelo**
See #73

### CODE REVIEW

**Comment by lbustelo** [comment]
@mariusvniekerk or @chipsenkbeil Can you take a look at this and merge into master? We already merged into 0.1.x and put out an RC2 with those changes.

**Comment by mariusvniekerk** [comment]
Sure I can do it.  Assume we just want a squashed commit for it.

**Comment by mariusvniekerk** [comment]
Do we have an associated jira?

**Comment by lbustelo** [comment]
no... it was based in #73 in response to RC1

**Comment by lbustelo** [comment]
Good catch. Would have to fix that in the 0.1.x branch. 

Gino B.

**Comment by mariusvniekerk** [comment]
If I'm marked as a maintainer on this repo and you tick the allow edits from maintainers i can do the fixes as needed.

**Comment by mariusvniekerk** [comment]
Somehow this made the tests use a different Scala version? Wonder if something is weird in how we install Java.

**Comment by mariusvniekerk** [comment]
Ah....  this is caused by basing the system-test image on 

jupyter/all-spark-notebook:07a7c4d6d447

which has the apache-toree pip package installed as toree.  This causes the imports to try do the wrong things somewhere along the chain?

**Comment by lbustelo** [comment]
@mariusvniekerk Lets hold off on this... I want to get to a successful release package on the 0.1.x branch and then we can push all the necessary changes at once in to master.

**Comment by mariusvniekerk** [comment]
Agree.  We'll also need to push some changes to jupyter docker stacks

**Comment by lbustelo** [comment]
I will close this one... We can do a more comprehensive PR once the 0.1.x release is accepted.

**Pull request closed without merging**
