### PR TITLE
[TOREE 277]: Added tutorial notebook for magics

### PR DESCRIPTION
**Pull request by Lull3rSkat3r**
This notebook should be left with the output so users can view the documentation properly in places like github and nbviewer.

### CODE REVIEW

**Comment by lbustelo** [comment]
@Lull3rSkat3r  Did you intend to push the tutorial with cell output?

**Comment by lbustelo** [comment]
Also, would be nice if have a similar template for all our examples. Look at the https://github.com/apache/incubator-toree/blob/master/etc/examples/notebooks/sqlcontext_sharing.ipynb. We should have table of contents and links to navigate back to the top.

**Comment by Lull3rSkat3r** [comment]
@lbustelo I can add the table of contents and links. Will add that and push.

**Comment by Lull3rSkat3r** [comment]
@lbustelo changes are pushed.

**Pull request merged**
