### PR TITLE
TOREE-413: Add exit commands and kernel idle timeout.

### PR DESCRIPTION
**Pull request by rdblue**
This adds support for "exit", "quit", and ":q" to exit Toree. It also adds a session idle timeout that defaults to 24h and a command-line option to control it.

### CODE REVIEW

**Comment by rdblue** [comment]
Looks like the tests for this one conflict with changes in #104. I'll update this once that one is merged.

**Comment by rdblue** [comment]
Rebased and fixed tests. I think this is good to go.

**Comment by mariusvniekerk** [comment]
LGTM! 

_Sent from my Google Pixel using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by rgbkrk** [comment]
LGTM!

_Sent from Disneyland_

**Comment by rdblue** [comment]
Thanks for reviewing, @mariusvniekerk! I rebased and will merge after tests pass.

**Pull request closed without merging**
