### PR TITLE
TOREE-319 Removing unnecesary guava dependency

### PR DESCRIPTION
**Pull request by fiskl**

### CODE REVIEW

**Comment by chipsenkbeil** [comment]
@lbustelo, @Lull3rSkat3r, do either of you remember why we explicitly brought in Guava? Was it for magic loading?

**Comment by Lull3rSkat3r** [comment]
@chipsenkbeil, yes it was there for filtering through the classes for loading magics. :shipit:

**Comment by fiskl** [comment]
In that case, could we use a repackaged guava, or at least a more modern version? The new cassandra drivers are now refusing to work below v16, but I believe the hadoop ecosystem is stuck on v14

**Comment by chipsenkbeil** [comment]
@Lull3rSkat3r, are you saying that we don't need Guava anymore since magics now use the plugin system?

**Comment by Lull3rSkat3r** [comment]
@chipsenkbeil, yes it is no longer needed.

**Comment by chipsenkbeil** [comment]
@fiskl, if you rebase, I can merge this in.

**Comment by fiskl** [comment]
Rebased and ready to go

**Comment by chipsenkbeil** [comment]
@fiskl, are you sure you rebased (last commit was 6 hours ago)? Looks like it is still behind master.

**Comment by fiskl** [comment]
It's the weekend, I'll blame that

**Comment by chipsenkbeil** [comment]
Thanks again for all the PRs! Loving the support!

**Pull request merged**
