### PR TITLE
[TOREE-382] Refactor sbt build

### PR DESCRIPTION
**Pull request by jodersky**
*These changes are the first part of a larger series of patches [TOREE-381] aiming to increase productivity by simplifying, stabilizing and speeding up the build and CI processes.*

- Consolidate dependencies into one file (`project/Dependencies.scala`)
- Factor out common behaviour into build-wide settings and auto-plugins
- Remove unused, non-essential sbt plugins
- Remove unused test config "scratch test"
- ~~Remove the "ivy rebuild XML" feature. *(I'm not sure why it was added in the first place, please shout out if the removal is wrong.)*~~

### CODE REVIEW

**Comment by mariusvniekerk** [comment]
So the ivy piece I believe was to help coursier avoid downloading spark dependencies with things like adddeps

**Comment by jodersky** [comment]
Ok, I'll add it back then

**Comment by jodersky** [comment]
rebased onto latest master

**Comment by rdblue** [comment]
@jodersky, @mariusvniekerk, I'm using a gradle-based build instead of sbt. Are you guys interested in having a gradle build script available in addition to sbt? I find it easier to work with and it matches our other projects. I completely understand if you only want one build, but I thought I'd offer since I have it working.

**Comment by mariusvniekerk** [comment]
@jodersky Okay for me to merge this in or do you still have some things you want to add to this?

**Comment by chipsenkbeil** [comment]
@rdblue, have you opened a PR for it? If not, do so. We can take a look to see how much effort it would be to maintain.

**Comment by jodersky** [comment]
@mariusvniekerk good to go!

**Comment by rdblue** [comment]
@chipsenkbeil, I opened PR #106 with the gradle build script. I hope it's useful.

**Pull request merged**
