### PR TITLE
adjustments for Java 11 and Spark 3.2.0

### PR DESCRIPTION
**Pull request by pikulmar**

### CODE REVIEW

**Comment by pikulmar** [comment]
This PR documents the adjustments necessary to make Toree work with Java 11 and Spark 3.1.2.

Is there any interest in having this integrated into upstream?

**Review by benbemoh — APPROVED** [review]
LGTM

**Comment by lresende** [comment]
let me take a look at it over the weekend.

**Comment by lresende** [comment]
@pikulmar please take a look at [this commit](https://github.com/lresende/incubator-toree/commit/1ea2a1d73affa9cf9d388b5f7457160365648813). I started trying the same but could not get the tests to run. Maybe you could add the CI changes to your PR and continue working on that as I am with limited time to help here.

**Comment by pikulmar** [comment]
@lresende Tests pass locally now (using Java 11)

**Comment by pikulmar** [comment]
@lresende Merged your work into this branch.

**Comment by pikulmar** [comment]
@lresende Can you already gauge whether / when your schedule could allow you to have a look at this PR?

**Comment by lresende** [comment]
Thanks @pikulmar. Could you [enable maintainers to edit your pr](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)? I want to try to force a build to it.

**Review by lresende — APPROVED** [review]

**Pull request merged**
