### PR TITLE
[TOREE-475] Resolve variables in sql statement

### PR DESCRIPTION
**Pull request by huafengw**

### CODE REVIEW

**Comment by huafengw** [comment]
Then the sql cell is able to do something like:


The variables are defined in previous Scala cells

**Comment by huafengw** [comment]
The failed `ExecuteRequestHandlerSpec` passed on my local machine.

**Comment by huafengw** [comment]
Hi @lresende, can you take a look at this one? Thanks!

**Comment by lresende** [comment]
LGTM, Rebasing and merging.

**Comment by lresende** [comment]
Clean build:
https://travis-ci.org/lresende/incubator-toree/builds/434428853

**Pull request closed without merging**
