### PR TITLE
Modifying travis to run a make target that tests and audits the code

### PR DESCRIPTION
**Pull request by lbustelo**
The goal is to automate as much checking as possible on a PR. This will now run RAT as part of travis build.

### CODE REVIEW

**Comment by lbustelo** [comment]
@Lull3rSkat3r Please check the results of Travis and if it looks like it did the test, RAT and clean, this should be good to merge.

**Comment by lbustelo** [comment]
I'm going to close and reopen the PR to force another build. This will test if the after-script is doing its job.

**Comment by lbustelo** [comment]
The rerun worked fine, I'll take it that it is cleaning up properly. There reason that I'm a bit sckeptical is that I see the caching happening before the `after_script`. So either it is caching the unlock, or this is just a problem that is needed under certain circumstances, such as a build failure.

@chipsenkbeil You remember the reason you had [this](https://github.com/apache/incubator-toree/blob/c3470855f8f7bf7a0cb03082d22fe1ef10f8da98/Makefile#L165)

**Comment by chipsenkbeil** [comment]
@lbustelo that came from instructions in sbt regarding using Travis' caching: http://www.scala-sbt.org/0.13/docs/Travis-CI-with-sbt.html#%28Experimental%29+Reusing+Ivy+cache

**Comment by lbustelo** [comment]
@chipsenkbeil Since I was able to run the PR twice, you think that the `after-script` is working?

**Comment by lbustelo** [comment]
https://docs.travis-ci.com/user/caching/#Build-phases points to the cache taking place before `after-script`. What if I unlock in `before-script`?

**Comment by lbustelo** [comment]
I think I'm going to switch the cleaning to happen on `before-cache` https://docs.travis-ci.com/user/caching/#before_cache-phase

**Comment by lbustelo** [comment]
@chipsenkbeil I think the shell commands are basically the same. I moved the target to `before-cache` and it all seemed to work.

Either @chipsenkbeil  or @Lull3rSkat3r , merge this when you get a chance.

**Comment by Lull3rSkat3r** [comment]
Merged in as commit https://github.com/apache/incubator-toree/commit/cea63655a47d55334492f532c8ce1a22b5a3a457

**Pull request closed without merging**
