### PR TITLE
Remove Experimental from Comm classes

### PR DESCRIPTION
**Pull request by krishnakalyan3**
Remove @Experimental from Comm classes
https://issues.apache.org/jira/browse/TOREE-263

### CODE REVIEW

**Comment by chipsenkbeil** [comment]
@krishnakalyan3, we're seeing the occasional test lockup. For some reason, it's happening a little more often than I remember. You can retrigger the tests by closing and reopening your PR.

@lbustelo, @Lull3rSkat3r, I thought we had stamped out the test hangup problem. Any thoughts as to what is causing this?

**Comment by krishnakalyan3** [comment]
@chipsenkbeil do you think the pull request looks okay?. I will close/reopen the PR. 
There were some @Experiment annotations in the file below which I did not remove `kernel/src/main/scala/org/apache/toree/kernel/api/Kernel.scala`.

**Comment by chipsenkbeil** [comment]
At this point, you can remove all of the `@Experimental` tags that you find. Those were added at the beginning of 2015; so, I see no reason to leave them on now when they have proven to be stable and the API is pretty consistent.

**Comment by Lull3rSkat3r** [comment]
@chipsenkbeil, no I don't know what could be the problem with the tests hanging. Created an issue for it: https://issues.apache.org/jira/browse/TOREE-326

**Comment by chipsenkbeil** [comment]
@krishnakalyan3, did you mean to close and delete your branch? If you were trying to re-run the tests, you can just close and then reopen. No need to delete your branch. If you're having issues, let us know via the mailing list or this PR.

**Pull request closed without merging**
